import { PartialType } from '@nestjs/mapped-types';
import { ApiProperty } from '@nestjs/swagger';
import { IsEmail } from 'class-validator';
import {
  CREATE_OR_UPDATE_PATIENT_NAME_DESCRIPTION,
  CREATE_OR_UPDATE_PATIENT_NAME_EXAMPLE,
  CREATE_OR_UPDATE_PATIENT_PHONE_DESCRIPTION,
  CREATE_OR_UPDATE_PATIENT_PHONE_EXAMPLE,
  CREATE_OR_UPDATE_PATIENT_EMAIL_DESCRIPTION,
  CREATE_OR_UPDATE_PATIENT_EMAIL_EXAMPLE,
  CREATE_OR_UPDATE_PATIENT_DOCUMENT_DESCRIPTION,
  CREATE_OR_UPDATE_PATIENT_DOCUMENT_EXAMPLE,
  CREATE_OR_UPDATE_PATIENT_BIRTHDAY_DESCRIPTION,
  CREATE_OR_UPDATE_PATIENT_BIRTHDAY_EXAMPLE,
  CREATE_OR_UPDATE_PATIENT_GENDER_DESCRIPTION,
  CREATE_OR_UPDATE_PATIENT_GENDER_EXAMPLE,
  CREATE_OR_UPDATE_PATIENT_HEIGHT_DESCRIPTION,
  CREATE_OR_UPDATE_PATIENT_HEIGHT_EXAMPLE,
  CREATE_OR_UPDATE_PATIENT_WEIGHT_DESCRIPTION,
  CREATE_OR_UPDATE_PATIENT_WEIGHT_EXAMPLE,
} from '../constants';
import { CreatePatientDto } from './create-patient.dto';

export class UpdatePatientDto extends PartialType(CreatePatientDto) {
  @ApiProperty({
    description: CREATE_OR_UPDATE_PATIENT_NAME_DESCRIPTION,
    example: CREATE_OR_UPDATE_PATIENT_NAME_EXAMPLE,
  })
  name?: string;
  @ApiProperty({
    description: CREATE_OR_UPDATE_PATIENT_PHONE_DESCRIPTION,
    example: CREATE_OR_UPDATE_PATIENT_PHONE_EXAMPLE,
  })
  phone?: string;
  @IsEmail()
  @ApiProperty({
    description: CREATE_OR_UPDATE_PATIENT_EMAIL_DESCRIPTION,
    example: CREATE_OR_UPDATE_PATIENT_EMAIL_EXAMPLE,
  })
  email?: string;
  @ApiProperty({
    description: CREATE_OR_UPDATE_PATIENT_DOCUMENT_DESCRIPTION,
    example: CREATE_OR_UPDATE_PATIENT_DOCUMENT_EXAMPLE,
  })
  document?: string;
  @ApiProperty({
    description: CREATE_OR_UPDATE_PATIENT_BIRTHDAY_DESCRIPTION,
    example: CREATE_OR_UPDATE_PATIENT_BIRTHDAY_EXAMPLE,
  })
  birthday?: string;
  @ApiProperty({
    description: CREATE_OR_UPDATE_PATIENT_GENDER_DESCRIPTION,
    example: CREATE_OR_UPDATE_PATIENT_GENDER_EXAMPLE,
  })
  gender?: string;
  @ApiProperty({
    description: CREATE_OR_UPDATE_PATIENT_HEIGHT_DESCRIPTION,
    example: CREATE_OR_UPDATE_PATIENT_HEIGHT_EXAMPLE,
  })
  height?: string;
  @ApiProperty({
    description: CREATE_OR_UPDATE_PATIENT_WEIGHT_DESCRIPTION,
    example: CREATE_OR_UPDATE_PATIENT_WEIGHT_EXAMPLE,
  })
  weight?: string;
}
