import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsNotEmpty, IsDateString } from 'class-validator';
import {
  CREATE_MEDICAL_CONSULTATION_NOTE_DTO_APPOINTMENT_ID_DESCRIPTION,
  CREATE_MEDICAL_CONSULTATION_NOTE_DTO_APPOINTMENT_ID_EXAMPLE,
  CREATE_MEDICAL_CONSULTATION_NOTE_DTO_DATE_DESCRIPTION,
  CREATE_MEDICAL_CONSULTATION_NOTE_DTO_DATE_EXAMPLE,
  CREATE_MEDICAL_CONSULTATION_NOTE_DTO_DOCTOR_NAME_DESCRIPTION,
  CREATE_MEDICAL_CONSULTATION_NOTE_DTO_DOCTOR_NAME_EXAMPLE,
  CREATE_MEDICAL_CONSULTATION_NOTE_DTO_NOTES_DESCRIPTION,
  CREATE_MEDICAL_CONSULTATION_NOTE_DTO_NOTES_EXAMPLE,
  CREATE_MEDICAL_CONSULTATION_NOTE_DTO_PATIENT_NAME_DESCRIPTION,
  CREATE_MEDICAL_CONSULTATION_NOTE_DTO_PATIENT_NAME_EXAMPLE,
} from '../constants';

export class CreateMedicalConsultationNoteDto {
  @IsNotEmpty()
  @IsString()
  @ApiProperty({
    description: CREATE_MEDICAL_CONSULTATION_NOTE_DTO_PATIENT_NAME_DESCRIPTION,
    example: CREATE_MEDICAL_CONSULTATION_NOTE_DTO_PATIENT_NAME_EXAMPLE,
  })
  patientName: string;

  @IsNotEmpty()
  @IsString()
  @ApiProperty({
    description: CREATE_MEDICAL_CONSULTATION_NOTE_DTO_DOCTOR_NAME_DESCRIPTION,
    example: CREATE_MEDICAL_CONSULTATION_NOTE_DTO_DOCTOR_NAME_EXAMPLE,
  })
  doctorName: string;

  @IsNotEmpty()
  @IsDateString()
  @ApiProperty({
    description: CREATE_MEDICAL_CONSULTATION_NOTE_DTO_DATE_DESCRIPTION,
    example: CREATE_MEDICAL_CONSULTATION_NOTE_DTO_DATE_EXAMPLE,
  })
  date: Date;

  @IsNotEmpty()
  @IsString()
  @ApiProperty({
    description: CREATE_MEDICAL_CONSULTATION_NOTE_DTO_NOTES_DESCRIPTION,
    example: CREATE_MEDICAL_CONSULTATION_NOTE_DTO_NOTES_EXAMPLE,
  })
  notes: string;

  @ApiProperty({
    description:
      CREATE_MEDICAL_CONSULTATION_NOTE_DTO_APPOINTMENT_ID_DESCRIPTION,
    example: CREATE_MEDICAL_CONSULTATION_NOTE_DTO_APPOINTMENT_ID_EXAMPLE,
    required: false,
  })
  appointmentId?: string;
}
